{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"   # in-cluster service, standalone mode - one pod, no LB needed
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "student-api-role"
          serviceAccountRef:
            name: eso-vault-auth
            namespace: student-api
{{- end }}
