apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Ajinkya-A3/Student-API.git
    targetRevision: main
    path: k8s/student-api

    helm:
      releaseName: student-api

  destination:
    server: https://kubernetes.default.svc
    namespace: student-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - '.spec.volumeClaimTemplates[] | .apiVersion'
        - '.spec.volumeClaimTemplates[] | .kind'