---
# Source: student-api/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: student-api-config
  namespace: student-api
data:
  APP_ENV: "production"
  APP_NAME: "Student API"
  APP_VERSION: "1.0.0"
  DB_DRIVER: "postgresql+psycopg"
  DB_HOST: "postgres"
  DB_NAME: "student_db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  POSTGRES_DB: "student_db"
  POSTGRES_USER: "postgres"
